force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>ExternalID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Game__c/fields/GameDate__c.field-meta.xml
<CustomField>
    <fullName>GameDate__c</fullName>
    <label>GameDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HomeTeam</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Games</relationshipLabel>
    <relationshipName>Games</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/HomeTeamScore__c.field-meta.xml
<CustomField>
    <fullName>HomeTeamScore__c</fullName>
    <label>HomeTeamScore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/PostSeason__c.field-meta.xml
<CustomField>
    <fullName>PostSeason__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PostSeason</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/VisitorTeam__c.field-meta.xml
<CustomField>
    <fullName>VisitorTeam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VisitorTeam</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Games (VisitorTeam)</relationshipLabel>
    <relationshipName>Games1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/VisitorTeamScore__c.field-meta.xml
<CustomField>
    <fullName>VisitorTeamScore__c</fullName>
    <label>VisitorTeamScore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Third party API id.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GamesService.cls
public with sharing class GamesService {

    public GamesService() {

    }
    public static Integer getTotalGames(){
        HttpResponse response = new Balldontlie().request(
                Balldontlie.REST_METHOD_GET, 
                Balldontlie.GAMES_API_PATH
        );
        if (response.getStatusCode() == Balldontlie.RESPONSE_CODE_SUCCESS) {
            GamesWrapper games = (GamesWrapper) JSON.deserialize(response.getBody(), GamesWrapper.class);
            return (Integer) games.meta.total_count;
        } else {
            throw new BalldontlieException(response.getBody());
        }
    }

    public static GamesWrapper getGamesByPage(Integer currrentPage, Integer perPage){
        HttpResponse response = new Balldontlie().request(
                Balldontlie.REST_METHOD_GET, 
                Balldontlie.GAMES_API_PATH + '?page='+currrentPage + 'per_page'+perPage
        );
        if (response.getStatusCode() == Balldontlie.RESPONSE_CODE_SUCCESS) {
            return (GamesWrapper) JSON.deserialize(response.getBody(), GamesWrapper.class);
        } else {
            throw new BalldontlieException(response.getBody());
        }
    }

    public static List<Game__c> convertGamesWrapperToGames(GamesWrapper wrapper){
        List<Game__c> gamesObjects = new List<Game__c>();
        List<GameEntity> gamesEntities = wrapper.data;
        for(GameEntity game: gamesEntities){
            gamesObjects.add(convertGameEntityToGame(game));
        }
        return gamesObjects;
    }
    public static Game__c convertGameEntityToGame(GameEntity game){
        Game__c gameObject = new Game__c(
            ExternalID__c = game.id,
            //GameDate__c = game.gamedate,
            HomeTeamScore__c = game.home_team_score,
            Period__c = game.period,
            PostSeason__c = game.postseason,
            Season__c = game.season,
            Status__c = game.status,
            VisitorTeamScore__c = game.visitor_team_score
        );
        Team__c hometeam = new Team__c(External_Id__c = game.home_team.id);
        Team__c visitorteam = new Team__c(External_Id__c = game.visitor_team.id);
        gameObject.HomeTeam__r = hometeam;
        gameObject.VisitorTeam__r = visitorteam;
        return gameObject;
    }
}