force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/HomeTeam__c.field-meta.xml
<CustomField>
    <fullName>HomeTeam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HomeTeam</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Games</relationshipLabel>
    <relationshipName>Games</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/HomeTeamScore__c.field-meta.xml
<CustomField>
    <fullName>HomeTeamScore__c</fullName>
    <label>HomeTeamScore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/VisitorTeam__c.field-meta.xml
<CustomField>
    <fullName>VisitorTeam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VisitorTeam</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Games (VisitorTeam)</relationshipLabel>
    <relationshipName>Games1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/VisitorTeamScore__c.field-meta.xml
<CustomField>
    <fullName>VisitorTeamScore__c</fullName>
    <label>VisitorTeamScore</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Game_Handler.cls
public without sharing class Game_Handler {

    public Game_Handler(){
        
    }

    public void onBeforeInsert(List<Game__c> triggerNew){
        setWinningTeam(triggerNew);
    }
    
    public void onBeforeUpdate(List<Game__c> triggerOld , List<Game__c> triggerNew , Map<Id,Game__c> triggerOldMap , Map<Id,Game__c> triggerNewMap){
        setWinningTeam(triggerNew);
    }

    public void onBeforeDelete(List<Game__c> triggerOld , Map<Id,Game__c> triggerOldMap){
    
    }

    public void onAfterInsert(List<Game__c> triggerNew , Map<Id,Game__c> triggerNewMap){
        calculateAverage(triggerNew);
    }

    public void onAfterUpdate(List<Game__c> triggerOld , List<Game__c> triggerNew , Map<Id,Game__c> triggerOldMap , Map<Id,Game__c> triggerNewMap){
        calculateAverage(triggerNew);
    }

    public void onAfterDelete(List<Game__c> triggerOld , Map<Id,Game__c> triggerOldMap){
        
    }

    public void onAfterUndelete(List<Game__c> triggerNew){
    
    }

    private static void setWinningTeam(List<Game__c> triggerNew){
        for(Game__c game: triggerNew){
            if(game.HomeTeamScore__c > game.VisitorTeamScore__c){
                game.WinnerTeam__c = game.HomeTeam__c;
            } else {
                game.WinnerTeam__c = game.VisitorTeam__c;
            }
        }
    }

    private static void calculateAverage(List<Game__c> triggerNew){
        Set<Id> teams = new Set<Id>();
        for(Game__c game: triggerNew){
            teams.add(game.hometeam__c);
            teams.add(game.visitorteam__c);
        }
        List<AggregateResult> allWon = GamesService.getCountAllWonGames(teams);
        Map<Id,Integer> mapAllWon = Util.listToMap(allWon);
        Map<Id,Integer> mapAllPlayed = GamesService.getCountAllPlayedGames(teams);

        List<Team__c> teamsToUpdate = new List<Team__c>();
        for(Id team: teams){
            Decimal average = (Decimal) (mapAllWon.get(team) / (Decimal) mapAllPlayed.get(team)) * 100;
            teamsToUpdate.add(new Team__c(Id = team, AverageWon__c = average));
        }
        update teamsToUpdate;
    }


}